/* ====================================================================
 *    Licensed to the Apache Software Foundation (ASF) under one
 *    or more contributor license agreements.  See the NOTICE file
 *    distributed with this work for additional information
 *    regarding copyright ownership.  The ASF licenses this file
 *    to you under the Apache License, Version 2.0 (the
 *    "License"); you may not use this file except in compliance
 *    with the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing,
 *    software distributed under the License is distributed on an
 *    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *    KIND, either express or implied.  See the License for the
 *    specific language governing permissions and limitations
 *    under the License.
 * ====================================================================
 */

#include <apr.h>
#include <apr_pools.h>
#include <apr_hash.h>

#include "serf.h"
#include "serf_private.h"


/* Character classes */
#define CT_ASCII        0x0001
#define CT_CNTRL        0x0002
#define CT_SPACE        0x0004
#define CT_PUNCT        0x0008
#define CT_DIGIT        0x0010
#define CT_UPPER        0x0020
#define CT_LOWER        0x0040
#define CT_XALPHA       0x0080
#define CT_UTF8_CONT    0x0100
#define CT_UTF8_LEAD    0x0200

/* Only space and the horizontal tab are treated as whitespace. */
#define CT_WHITESPACE 0x010000

/* A `token` is a sequence of ASCII digits, lowercase and uppercase letters,
   and the following punctiation marks:

       ! # $ % & ' * + - . ^ _ ` | ~

   See: https://www.rfc-editor.org/rfc/rfc9110.html#section-5.6.2
*/
#define CT_TOKEN      0x020000

/* A `token68` is a sequence of ASCII digits, lowercase and uppercase letters,
   and the following punctiation marks:

       - . _ ~ + /

   followed by zero or more `=` signs.
   See: https://www.rfc-editor.org/rfc/rfc9110.html#section-11.2
*/
#define CT_TOKEN68    0x040000


/* ASCII + UTF-8 character table, stolen wholesale from Subversion. */
static const apr_uint32_t char_table[256] =
{
    /* **** DO NOT EDIT! ****
       This table was generated by genctype.py, make changes there. */
    /* nul */ CT_ASCII | CT_CNTRL,
    /* soh */ CT_ASCII | CT_CNTRL,
    /* stx */ CT_ASCII | CT_CNTRL,
    /* etx */ CT_ASCII | CT_CNTRL,
    /* eot */ CT_ASCII | CT_CNTRL,
    /* enq */ CT_ASCII | CT_CNTRL,
    /* ack */ CT_ASCII | CT_CNTRL,
    /* bel */ CT_ASCII | CT_CNTRL,
    /* bs  */ CT_ASCII | CT_CNTRL,
    /* ht  */ CT_ASCII | CT_CNTRL | CT_SPACE | CT_WHITESPACE,
    /* nl  */ CT_ASCII | CT_CNTRL | CT_SPACE,
    /* vt  */ CT_ASCII | CT_CNTRL | CT_SPACE,
    /* np  */ CT_ASCII | CT_CNTRL | CT_SPACE,
    /* cr  */ CT_ASCII | CT_CNTRL | CT_SPACE,
    /* so  */ CT_ASCII | CT_CNTRL,
    /* si  */ CT_ASCII | CT_CNTRL,
    /* dle */ CT_ASCII | CT_CNTRL,
    /* dc1 */ CT_ASCII | CT_CNTRL,
    /* dc2 */ CT_ASCII | CT_CNTRL,
    /* dc3 */ CT_ASCII | CT_CNTRL,
    /* dc4 */ CT_ASCII | CT_CNTRL,
    /* nak */ CT_ASCII | CT_CNTRL,
    /* syn */ CT_ASCII | CT_CNTRL,
    /* etb */ CT_ASCII | CT_CNTRL,
    /* can */ CT_ASCII | CT_CNTRL,
    /* em  */ CT_ASCII | CT_CNTRL,
    /* sub */ CT_ASCII | CT_CNTRL,
    /* esc */ CT_ASCII | CT_CNTRL,
    /* fs  */ CT_ASCII | CT_CNTRL,
    /* gs  */ CT_ASCII | CT_CNTRL,
    /* rs  */ CT_ASCII | CT_CNTRL,
    /* us  */ CT_ASCII | CT_CNTRL,
    /* sp  */ CT_ASCII | CT_SPACE | CT_WHITESPACE,
    /*  !  */ CT_ASCII | CT_PUNCT | CT_TOKEN,
    /*  "  */ CT_ASCII | CT_PUNCT,
    /*  #  */ CT_ASCII | CT_PUNCT | CT_TOKEN,
    /*  $  */ CT_ASCII | CT_PUNCT | CT_TOKEN,
    /*  %  */ CT_ASCII | CT_PUNCT | CT_TOKEN,
    /*  &  */ CT_ASCII | CT_PUNCT | CT_TOKEN,
    /*  '  */ CT_ASCII | CT_PUNCT | CT_TOKEN,
    /*  (  */ CT_ASCII | CT_PUNCT,
    /*  )  */ CT_ASCII | CT_PUNCT,
    /*  *  */ CT_ASCII | CT_PUNCT | CT_TOKEN,
    /*  +  */ CT_ASCII | CT_PUNCT | CT_TOKEN | CT_TOKEN68,
    /*  ,  */ CT_ASCII | CT_PUNCT,
    /*  -  */ CT_ASCII | CT_PUNCT | CT_TOKEN | CT_TOKEN68,
    /*  .  */ CT_ASCII | CT_PUNCT | CT_TOKEN | CT_TOKEN68,
    /*  /  */ CT_ASCII | CT_PUNCT | CT_TOKEN68,
    /*  0  */ CT_ASCII | CT_DIGIT,
    /*  1  */ CT_ASCII | CT_DIGIT,
    /*  2  */ CT_ASCII | CT_DIGIT,
    /*  3  */ CT_ASCII | CT_DIGIT,
    /*  4  */ CT_ASCII | CT_DIGIT,
    /*  5  */ CT_ASCII | CT_DIGIT,
    /*  6  */ CT_ASCII | CT_DIGIT,
    /*  7  */ CT_ASCII | CT_DIGIT,
    /*  8  */ CT_ASCII | CT_DIGIT,
    /*  9  */ CT_ASCII | CT_DIGIT,
    /*  :  */ CT_ASCII | CT_PUNCT,
    /*  ;  */ CT_ASCII | CT_PUNCT,
    /*  <  */ CT_ASCII | CT_PUNCT,
    /*  =  */ CT_ASCII | CT_PUNCT,
    /*  >  */ CT_ASCII | CT_PUNCT,
    /*  ?  */ CT_ASCII | CT_PUNCT,
    /*  @  */ CT_ASCII | CT_PUNCT,
    /*  A  */ CT_ASCII | CT_UPPER | CT_XALPHA,
    /*  B  */ CT_ASCII | CT_UPPER | CT_XALPHA,
    /*  C  */ CT_ASCII | CT_UPPER | CT_XALPHA,
    /*  D  */ CT_ASCII | CT_UPPER | CT_XALPHA,
    /*  E  */ CT_ASCII | CT_UPPER | CT_XALPHA,
    /*  F  */ CT_ASCII | CT_UPPER | CT_XALPHA,
    /*  G  */ CT_ASCII | CT_UPPER,
    /*  H  */ CT_ASCII | CT_UPPER,
    /*  I  */ CT_ASCII | CT_UPPER,
    /*  J  */ CT_ASCII | CT_UPPER,
    /*  K  */ CT_ASCII | CT_UPPER,
    /*  L  */ CT_ASCII | CT_UPPER,
    /*  M  */ CT_ASCII | CT_UPPER,
    /*  N  */ CT_ASCII | CT_UPPER,
    /*  O  */ CT_ASCII | CT_UPPER,
    /*  P  */ CT_ASCII | CT_UPPER,
    /*  Q  */ CT_ASCII | CT_UPPER,
    /*  R  */ CT_ASCII | CT_UPPER,
    /*  S  */ CT_ASCII | CT_UPPER,
    /*  T  */ CT_ASCII | CT_UPPER,
    /*  U  */ CT_ASCII | CT_UPPER,
    /*  V  */ CT_ASCII | CT_UPPER,
    /*  W  */ CT_ASCII | CT_UPPER,
    /*  X  */ CT_ASCII | CT_UPPER,
    /*  Y  */ CT_ASCII | CT_UPPER,
    /*  Z  */ CT_ASCII | CT_UPPER,
    /*  [  */ CT_ASCII | CT_PUNCT,
    /*  \  */ CT_ASCII | CT_PUNCT,
    /*  ]  */ CT_ASCII | CT_PUNCT,
    /*  ^  */ CT_ASCII | CT_PUNCT | CT_TOKEN,
    /*  _  */ CT_ASCII | CT_PUNCT | CT_TOKEN | CT_TOKEN68,
    /*  `  */ CT_ASCII | CT_PUNCT | CT_TOKEN,
    /*  a  */ CT_ASCII | CT_LOWER | CT_XALPHA,
    /*  b  */ CT_ASCII | CT_LOWER | CT_XALPHA,
    /*  c  */ CT_ASCII | CT_LOWER | CT_XALPHA,
    /*  d  */ CT_ASCII | CT_LOWER | CT_XALPHA,
    /*  e  */ CT_ASCII | CT_LOWER | CT_XALPHA,
    /*  f  */ CT_ASCII | CT_LOWER | CT_XALPHA,
    /*  g  */ CT_ASCII | CT_LOWER,
    /*  h  */ CT_ASCII | CT_LOWER,
    /*  i  */ CT_ASCII | CT_LOWER,
    /*  j  */ CT_ASCII | CT_LOWER,
    /*  k  */ CT_ASCII | CT_LOWER,
    /*  l  */ CT_ASCII | CT_LOWER,
    /*  m  */ CT_ASCII | CT_LOWER,
    /*  n  */ CT_ASCII | CT_LOWER,
    /*  o  */ CT_ASCII | CT_LOWER,
    /*  p  */ CT_ASCII | CT_LOWER,
    /*  q  */ CT_ASCII | CT_LOWER,
    /*  r  */ CT_ASCII | CT_LOWER,
    /*  s  */ CT_ASCII | CT_LOWER,
    /*  t  */ CT_ASCII | CT_LOWER,
    /*  u  */ CT_ASCII | CT_LOWER,
    /*  v  */ CT_ASCII | CT_LOWER,
    /*  w  */ CT_ASCII | CT_LOWER,
    /*  x  */ CT_ASCII | CT_LOWER,
    /*  y  */ CT_ASCII | CT_LOWER,
    /*  z  */ CT_ASCII | CT_LOWER,
    /*  {  */ CT_ASCII | CT_PUNCT,
    /*  |  */ CT_ASCII | CT_PUNCT | CT_TOKEN,
    /*  }  */ CT_ASCII | CT_PUNCT,
    /*  ~  */ CT_ASCII | CT_PUNCT | CT_TOKEN | CT_TOKEN68,
    /* del */ CT_ASCII | CT_CNTRL,
    /* x80 */ CT_UTF8_CONT,
    /* x81 */ CT_UTF8_CONT,
    /* x82 */ CT_UTF8_CONT,
    /* x83 */ CT_UTF8_CONT,
    /* x84 */ CT_UTF8_CONT,
    /* x85 */ CT_UTF8_CONT,
    /* x86 */ CT_UTF8_CONT,
    /* x87 */ CT_UTF8_CONT,
    /* x88 */ CT_UTF8_CONT,
    /* x89 */ CT_UTF8_CONT,
    /* x8a */ CT_UTF8_CONT,
    /* x8b */ CT_UTF8_CONT,
    /* x8c */ CT_UTF8_CONT,
    /* x8d */ CT_UTF8_CONT,
    /* x8e */ CT_UTF8_CONT,
    /* x8f */ CT_UTF8_CONT,
    /* x90 */ CT_UTF8_CONT,
    /* x91 */ CT_UTF8_CONT,
    /* x92 */ CT_UTF8_CONT,
    /* x93 */ CT_UTF8_CONT,
    /* x94 */ CT_UTF8_CONT,
    /* x95 */ CT_UTF8_CONT,
    /* x96 */ CT_UTF8_CONT,
    /* x97 */ CT_UTF8_CONT,
    /* x98 */ CT_UTF8_CONT,
    /* x99 */ CT_UTF8_CONT,
    /* x9a */ CT_UTF8_CONT,
    /* x9b */ CT_UTF8_CONT,
    /* x9c */ CT_UTF8_CONT,
    /* x9d */ CT_UTF8_CONT,
    /* x9e */ CT_UTF8_CONT,
    /* x9f */ CT_UTF8_CONT,
    /* xa0 */ CT_UTF8_CONT,
    /* xa1 */ CT_UTF8_CONT,
    /* xa2 */ CT_UTF8_CONT,
    /* xa3 */ CT_UTF8_CONT,
    /* xa4 */ CT_UTF8_CONT,
    /* xa5 */ CT_UTF8_CONT,
    /* xa6 */ CT_UTF8_CONT,
    /* xa7 */ CT_UTF8_CONT,
    /* xa8 */ CT_UTF8_CONT,
    /* xa9 */ CT_UTF8_CONT,
    /* xaa */ CT_UTF8_CONT,
    /* xab */ CT_UTF8_CONT,
    /* xac */ CT_UTF8_CONT,
    /* xad */ CT_UTF8_CONT,
    /* xae */ CT_UTF8_CONT,
    /* xaf */ CT_UTF8_CONT,
    /* xb0 */ CT_UTF8_CONT,
    /* xb1 */ CT_UTF8_CONT,
    /* xb2 */ CT_UTF8_CONT,
    /* xb3 */ CT_UTF8_CONT,
    /* xb4 */ CT_UTF8_CONT,
    /* xb5 */ CT_UTF8_CONT,
    /* xb6 */ CT_UTF8_CONT,
    /* xb7 */ CT_UTF8_CONT,
    /* xb8 */ CT_UTF8_CONT,
    /* xb9 */ CT_UTF8_CONT,
    /* xba */ CT_UTF8_CONT,
    /* xbb */ CT_UTF8_CONT,
    /* xbc */ CT_UTF8_CONT,
    /* xbd */ CT_UTF8_CONT,
    /* xc5 */ CT_UTF8_LEAD,
    /* xc6 */ CT_UTF8_LEAD,
    /* xc7 */ CT_UTF8_LEAD,
    /* xc8 */ CT_UTF8_LEAD,
    /* xc9 */ CT_UTF8_LEAD,
    /* xca */ CT_UTF8_LEAD,
    /* xcb */ CT_UTF8_LEAD,
    /* xcc */ CT_UTF8_LEAD,
    /* xcd */ CT_UTF8_LEAD,
    /* xce */ CT_UTF8_LEAD,
    /* xcf */ CT_UTF8_LEAD,
    /* xd0 */ CT_UTF8_LEAD,
    /* xd1 */ CT_UTF8_LEAD,
    /* xd2 */ CT_UTF8_LEAD,
    /* xd3 */ CT_UTF8_LEAD,
    /* xd4 */ CT_UTF8_LEAD,
    /* xd5 */ CT_UTF8_LEAD,
    /* xd6 */ CT_UTF8_LEAD,
    /* xd7 */ CT_UTF8_LEAD,
    /* xd8 */ CT_UTF8_LEAD,
    /* xd9 */ CT_UTF8_LEAD,
    /* xda */ CT_UTF8_LEAD,
    /* xdb */ CT_UTF8_LEAD,
    /* xdc */ CT_UTF8_LEAD,
    /* xdd */ CT_UTF8_LEAD,
    /* xde */ CT_UTF8_LEAD,
    /* xdf */ CT_UTF8_LEAD,
    /* xe0 */ 0,
    /* xe1 */ CT_UTF8_LEAD,
    /* xe2 */ CT_UTF8_LEAD,
    /* xe3 */ CT_UTF8_LEAD,
    /* xe4 */ CT_UTF8_LEAD,
    /* xe5 */ CT_UTF8_LEAD,
    /* xe6 */ CT_UTF8_LEAD,
    /* xe7 */ CT_UTF8_LEAD,
    /* xe8 */ CT_UTF8_LEAD,
    /* xe9 */ CT_UTF8_LEAD,
    /* xea */ CT_UTF8_LEAD,
    /* xeb */ CT_UTF8_LEAD,
    /* xec */ CT_UTF8_LEAD,
    /* xed */ CT_UTF8_LEAD,
    /* xee */ CT_UTF8_LEAD,
    /* xef */ CT_UTF8_LEAD,
    /* xf0 */ 0,
    /* xf1 */ CT_UTF8_LEAD,
    /* xf2 */ CT_UTF8_LEAD,
    /* xf3 */ CT_UTF8_LEAD,
    /* xf4 */ CT_UTF8_LEAD,
    /* xf5 */ CT_UTF8_LEAD,
    /* xf6 */ CT_UTF8_LEAD,
    /* xf7 */ CT_UTF8_LEAD,
    /* xf8 */ 0,
    /* xf9 */ CT_UTF8_LEAD,
    /* xfa */ CT_UTF8_LEAD,
    /* xfb */ CT_UTF8_LEAD,
    /* xfc */ 0,
    /* xfd */ CT_UTF8_LEAD,
    /* xfe */ 0,
    /* xff */ 0
};

/* Character class lookup */
static APR_INLINE int ct_isspace(char c)
{
    return char_table[(unsigned char)c] & CT_WHITESPACE;
}

static APR_INLINE int ct_istoken(char c)
{
    static const apr_uint32_t ct = CT_TOKEN | CT_DIGIT | CT_UPPER | CT_LOWER;
    return ct & char_table[(unsigned char)c];
}

static APR_INLINE int ct_istoken68(char c)
{
    static const apr_uint32_t ct = CT_TOKEN68 | CT_DIGIT | CT_UPPER | CT_LOWER;
    return ct & char_table[(unsigned char)c];
}


/* Uppercase-lowercase table, also stolen wholesale from Subversion.
   Folds uppercase ASCII letters into lowercase and ignores the rest. */
static const unsigned char casefold_table[256] =
  {
    /* Identity, except {65:90} => {97:122} */
      0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
     16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
     32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
     48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
     64, 97, 98, 99,100,101,102,103,104,105,106,107,108,109,110,111,
    112,113,114,115,116,117,118,119,120,121,122, 91, 92, 93, 94, 95,
     96, 97, 98, 99,100,101,102,103,104,105,106,107,108,109,110,111,
    112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,
    128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,
    144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,
    160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,
    176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,
    192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,
    208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,
    224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,
    240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255
  };

/* Fold ASCII to lowercase. */
static APR_INLINE char ct_tolower(char c)
{
    return (char) casefold_table[(unsigned char)c];
}


static const char *skip_space(const char *src)
{
    while (ct_isspace(*src))
        ++src;
    return src;
}

static const char *skip_token68(const char *src)
{
    while (ct_istoken68(*src))
        ++src;
    while (*src == '=')
        ++src;
    return src;
}

#if 0
static const char *skip_comment(const char *src)
{
    if (*src != '(')
        return NULL;

    ++src;
    while (*src && *src != ')')
    {
        if (*src == '(') {
            src = skip_comment(src);
            if (!src)
                return NULL;
        }
        else {
            if (*src == '\\')
                ++src;          /* Skip escape from quoted-pair */
            if (*src)
                ++src;
        }
    }

    if (!*src)
        return NULL;
    return src + 1;
}
#endif

static const char *copy_quoted_string(char **dst, const char *src)
{
    if (*src != '"')
        return NULL;

    ++src;
    while (*src && *src != '"')
    {
        if (*src == '\\')
            ++src;              /* Skip escape from quoted-pair */
        if (*src)
            *((*dst)++) = *src++;
    }

    if (!*src)
        return NULL;
    return src + 1;
}

static const char *copy_token_key(char **dst, const char *src)
{
    if (!ct_istoken(*src))
        return NULL;

    do { *((*dst)++) = ct_tolower(*src++); } while (ct_istoken(*src));
    return src;
}

static const char *copy_token(char **dst, const char *src)
{
    if (!ct_istoken(*src))
        return NULL;

    do { *((*dst)++) = *src++; } while (ct_istoken(*src));
    return src;
}


apr_hash_t *serf__parse_authn_parameters(const char *attrs, apr_pool_t *pool)
{
    apr_hash_t *dict = apr_hash_make(pool);
    char *dst = apr_palloc(pool, strlen(attrs) + 1);
    const char *src = skip_space(attrs);
    const char *end = skip_token68(src);
    bool want_comma = false;

    /* Check if the parameters are a single token68. */
    if (end != src && !*skip_space(end)) {
        memcpy(dst, src, end - src);
        dst[end - src] = '\0';
        apr_hash_set(dict, "", 0, dst);
        return dict;
    }

    while (src && *src)
    {
        const char *key;
        apr_ssize_t keylen;
        const char *value;

        /* Skip spaces and the separator. */
        src = skip_space(src);
        if (want_comma) {
            if (*src != ',')
                break;
            ++src;
            if (*src)
                src = skip_space(src);
        }
        if (!*src)
            break;

        /* Pars the key, a lower-cased token. */
        key = dst;
        src = copy_token_key(&dst, src);
        if (!src || key == dst || *src != '=')
            break;
        keylen = dst - key;
        *dst++ = '\0';

        /* Parse the value, either a token or a quoted string. */
        ++src;
        value = dst;
        if (*src == '"')
            src = copy_quoted_string(&dst, src);
        else if (ct_istoken(*src))
            src = copy_token(&dst, src);
        if (!src || value == dst)
            break;
        *dst++ = '\0';

        /* Must be at the end of the string or at a valid separator. */
        src = skip_space(src);
        if (*src && *src != ',')
            break;

        /* Put the new key/value pair into the dict. */
        apr_hash_set(dict, key, keylen, value);
        want_comma = true;
    }

    return dict;
}


void serf__tolower_inplace(char *dst)
{
    while(*dst) {
        *dst = ct_tolower(*dst);
        ++dst;
    }
}


const char *serf__tolower(const char *src, apr_pool_t *pool)
{
    const size_t len = strlen(src) + 1;
    size_t i;

    char *dst = apr_palloc(pool, len);
    for (i = 0; i < len; ++i)
        dst[i] = ct_tolower(src[i]); /* The NUL byte is copied, too. */
    return dst;
}
