name: Linux

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "trunk" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install scons libapr1 libapr1-dev libaprutil1 libaprutil1-dev zlib1g zlib1g-dev libssl-dev

      - uses: actions/checkout@v3

      - name: Build
        run: scons

      - name: Check
        run: scons check
