name: Linux (SCons)

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "trunk" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ "ubuntu-22.04", "ubuntu-24.04" ]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get -y install scons libapr1-dev libaprutil1-dev zlib1g-dev libssl-dev libbrotli-dev libkrb5-dev

      - uses: actions/checkout@v6

      - name: Build
        run: scons BROTLI=/usr GSSAPI=/usr

      - name: Check
        run: scons check
