name: Linux (CMake)

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "trunk" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ "ubuntu-20.04", "ubuntu-22.04" ]
        build-type: [Debug, Release]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install libapr1 libapr1-dev libaprutil1 libaprutil1-dev zlib1g zlib1g-dev libssl-dev

      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{ matrix.build-type }}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{ matrix.build-type }} --output-on-failure
